#!/usr/bin/env bash
set -ex -o pipefail

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

case "$1" in

 jitpack)
   exec $0 mill -j 0 __.publishM2Local
 ;;

 servor)
   exec npx servor ${2:-"gh-pages"} ${3:-"index.html"} 8888 --reload --browse --static
 ;;

 gh-pages)
   $0 mill -j 0 '{__.docJar,examples.__.fastOpt}'
   find out -path '*docJar/dest/out.jar' | xargs -IFILE bash -c 'jar -xf FILE -C $(dirname FILE) /'
   mkdir -p gh-pages
   cp -rfv docs/index* docs/404* README.md docs/ examples/ gh-pages/
   find out/ -path '*fastOpt/dest/out*' | cpio -p -dumv gh-pages/
   find out/ -path '*docJar/dest/javadoc/*' | cpio -p -dumv gh-pages/
   find gh-pages/docs -type d -exec touch {}/.nojekyll \;
 ;;

 cs)
   test -x cs || {
     curl -o cs -qL https://git.io/coursier-cli
     chmod +x cs
   }
   exec ./cs "${@:2}"
 ;;

 scalafmt)
   exec $0 cs launch scalafmt -- --mode diff --diff-branch master "${@:2}"
 ;;

 scalafmt-test)
   exec $0 scalafmt --test
 ;;

 mdoc-gen)
   $0 mill drivers.all._.mdocProperties
   $0 mdoc-js -i docs/doc1.md -o docs/doc2.md
 ;;

 mdoc)
   exec $0 mdoc- "" "${@:2}"
 ;;

 mdoc-js)
   exec $0 mdoc- -js "${@:2}"
 ;;

 mdoc-)
   exec $0 cs launch org.scalameta:mdoc${2}_2.12:2.2.0 --extra-jars out/drivers/all/mdocProperties/dest/ -- "${@:3}"
 ;;

 mill)
   exec $0 cs launch --scala "$(awk '/^scala/{print$2}' $BASE_DIR/.tool-versions)" mill:"$(< $BASE_DIR/.mill-version)" -- "${@:2}"
 ;;

 mill-i)
   exec $0 cs launch --scala "$(awk '/^scala/{print$2}' $BASE_DIR/.tool-versions)"  mill-interactive:"$(< $BASE_DIR/.mill-version)" -- -i "${@:2}"
 ;;

 test)
   exec $0 mill -j 0 __.compile
 ;;

 example)
   trap "trap - SIGTERM && kill -9 -- -$$" SIGINT SIGTERM SIGKILL EXIT
   $0 mill -w "examples.{__.fastOpt,serve}" "$2"
 ;;

esac
