#!/usr/bin/env bash
set -ex -o pipefail

mkdir -p $HOME/bin
export PATH=$HOME/bin:$PATH

case "$*" in

 jitpack)
   mill -i '{cycle,drivers._}.publishM2Local'
 ;;

 gh-pages)
   mill -i '{cycle.docJar,drivers._.docJar,examples._.fastOpt}'
   find out -path '*docJar/dest/out.jar' | xargs -IFILE bash -c 'jar -xf FILE -C $(dirname FILE) /'
   mkdir -p gh-pages
   cp -rf README.md examples/ gh-pages/
   find out/ -path '*fastOpt/dest/out*' | cpio -p -dum gh-pages/
   find out/ -path '*docJar/dest/javadoc/*' | cpio -p -dum gh-pages/
 ;;

 scalafmt)
   curl -o cs -qL https://git.io/coursier-cli
   chmod +x cs
   ./cs launch scalafmt -- --mode diff --diff-branch master
 ;;

 scalafmt-test)
   curl -o cs -qL https://git.io/coursier-cli
   chmod +x cs
   ./cs launch scalafmt -- --mode diff --diff-branch master --test
 ;;

 "jitpack deps")
     # asdf depends on column and asdf-java depends on jq,
     # however it seems there's no way to install system dependencies on jitpack container.
     # We just install mill and set a jdk on jitpack.yml
     echo installing mill via curl
     mill_version=$(awk '/mill/ {print $2}' .tool-versions)
     curl -o $HOME/bin/mill -L https://github.com/lihaoyi/mill/releases/download/$mill_version/$mill_version
     chmod +x $HOME/bin/mill
 ;;

 test)
   mill -i __.compile
 ;;

esac
